apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acr-secret-staging-docker-std
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: acr-secret-staging-docker-std
    template:
      type: Opaque
      data:
        username: "skyacrstagingj3minh"
        password: "{{ .password }}"
        # ArgoCD Image Updater can also read 'acr-password' key directly if needed, but let's stick to standard names
  data:
  - secretKey: password
    remoteRef:
      key: acr-password
