---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      vaultUrl: "https://akv-sky-staging-a56c7aad.vault.azure.net"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
