---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regcred
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: regcred
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "skyacrstagingj3minh.azurecr.io": {
                "username": "skyacrstagingj3minh",
                "password": "{{ .password }}",
                "auth": "{{ printf "skyacrstagingj3minh:%s" .password | b64enc }}"
              }
            }
          }
  data:
  - secretKey: password
    remoteRef:
      key: acr-password
