apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-staging
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://akv-sky-staging-a56c7aad.vault.azure.net
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regcred
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-staging
    kind: ClusterSecretStore
  target:
    name: regcred
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "skyacrstagingj3minh.azurecr.io": {
                "username": "skyacrstagingj3minh",
                "password": "{{ .password }}",
                "auth": "{{ printf "skyacrstagingj3minh:%s" .password | b64enc }}"
              }
            }
          }
  data:
  - secretKey: password
    remoteRef:
      key: acr-password
