apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sky-frontend-staging-common-app
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sky.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sky-frontend-staging-common-app
            port:
              number: 80
  - host: "68.220.132.21"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sky-frontend-staging-common-app
            port:
              number: 80
