sonar.projectKey=sky-first_sky-poc-infra
sonar.organization=sky-first
sonar.projectName=sky-poc-infra
sonar.projectVersion=1.0

# Path to sources
sonar.sources=.
sonar.exclusions=**/*.test.js, **/test_*.py, infra/aks/bastion_key*, docs/**, scripts/test_vulnerable_reqs.txt

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Language specific properties
sonar.python.version=3
sonar.javascript.environments=node
