{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common-app.fullname" . }}-migrate
  labels:
    {{- include "common-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: {{ include "common-app.fullname" . }}-migrate
      labels:
        {{- include "common-app.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: {{ .Values.migration.command | toJson }}
          args: {{ .Values.migration.args | toJson }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "common-app.fullname" . }}-secrets
                  key: database-url
                  optional: true
{{- end }}
