{{- if .Values.envSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common-app.fullname" . }}-secrets
  labels:
    {{- include "common-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.envSecrets }}
  {{- if kindIs "string" $val }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}
