---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-staging
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: postgres-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-staging
    kind: ClusterSecretStore
  target:
    name: redis-secret
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: redis-password
