helm:
  parameters:
  - name: image.name
    value: skyacrprodel5zpw.azurecr.io/sky-poc-ai
    forcestring: true
  - name: image.tag
    value: sha-ba79e993563781553488798d744224916cf13436
    forcestring: true
