helm:
  parameters:
  - name: image.repository
    value: skyacrstagingj3minh.azurecr.io/sky-poc-frontend
    forcestring: true
  - name: image.tag
    value: sha-663a50314cd68810213dd7901cf59f7b9b45cf4b
    forcestring: true
