helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-ai
    forcestring: true
  - name: image.tag
    value: sha-d5879b4fb105f64a1327c8f1765402ec8e68b8f6
    forcestring: true
