helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-backend
    forcestring: true
  - name: image.tag
    value: sha-5f1113fb81302b3616cace4a32c4ff8b2a7a19a1
    forcestring: true
