helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-ai
    forcestring: true
  - name: image.tag
    value: sha-14118410b22021b45febda230fa960730094ccb0
    forcestring: true
