helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-backend
    forcestring: true
  - name: image.tag
    value: sha-7e7db4c15495ca4582f6caad90f2d333c9d302a4
    forcestring: true
