helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-backend
    forcestring: true
  - name: image.tag
    value: sha-dfe02f6b260bd4f3e7a1a3035fcfcbba7c87bc37
    forcestring: true
