helm:
  parameters:
  - name: image.name
    value: skyacrprodel5zpw.azurecr.io/sky-poc-frontend
    forcestring: true
  - name: image.tag
    value: sha-bc8a863831e99292a86a911011c9ab1696b6a1bf
    forcestring: true
