helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-backend
    forcestring: true
  - name: image.tag
    value: sha-65cddeb96df2bdde8f85e34d69f15e727be48688
    forcestring: true
