helm:
  parameters:
  - name: image.repository
    value: skyacrstagingj3minh.azurecr.io/sky-poc-frontend
    forcestring: true
  - name: image.tag
    value: sha-6ff93b62e48dbc8b0ebb386c0d4540be62404e64
    forcestring: true
