helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-backend
    forcestring: true
  - name: image.tag
    value: sha-1bc3f0325bb693d3a3fcec902354a8ec04c75dac
    forcestring: true
