helm:
  parameters:
  - name: image.repository
    value: skyacrstagingj3minh.azurecr.io/sky-poc-frontend
    forcestring: true
  - name: image.tag
    value: sha-f493aa724bd01a57d8a511900a393fd27c5a3953
    forcestring: true
