helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-backend
    forcestring: true
  - name: image.tag
    value: sha-966afababc2fc88037361489c2fa347f4579bee6
    forcestring: true
