helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-backend
    forcestring: true
  - name: image.tag
    value: sha-c62dba3cf7f2d802cc1f7f4c9b3085e33595c13f
    forcestring: true
