helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-frontend
    forcestring: true
  - name: image.tag
    value: sha-164070a6ccfcb518c0f37aa3f75b298b33b8df28
    forcestring: true
