helm:
  parameters:
  - name: image.name
    value: skyacrstagingj3minh.azurecr.io/sky-poc-backend
    forcestring: true
  - name: image.tag
    value: sha-ff13da0547bbddf004af46917d2545a4be3eec50
    forcestring: true
