helm:
  parameters:
  - name: image.repository
    value: skyacrstagingj3minh.azurecr.io/sky-poc-frontend
    forcestring: true
  - name: image.tag
    value: sha-069e8bb0976bcf9b4379c3aed5037a557f7726c6
    forcestring: true
