image:
  tag: "sha-65fb2f25663c17a43287b6eef4861d15d522c193"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/modsecurity-snippet: "SecRuleRemoveById 942100"
  hosts:
    - host: teamblue.skyfirstlabs.com
      paths:
        - path: /
          pathType: Prefix
    - host: platform.teamblue-stg.skyfirstlabs.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: teamblue-fe-stg-tls
      hosts:
        - teamblue.skyfirstlabs.com
        - platform.teamblue-stg.skyfirstlabs.com

service:
  port: 80
  targetPort: 3000

replicaCount: 1

extraEnv:
  - name: NEXT_PUBLIC_API_URL
    value: "https://platform.teamblue-stg.skyfirstlabs.com"
  - name: NEXTAUTH_URL
    value: "https://platform.teamblue-stg.skyfirstlabs.com"
