---
helm:
  parameters:
  - name: image.name
    value: skyacrprodel5zpw.azurecr.io/sky-poc-ai
    forcestring: true
  - name: image.tag
    value: sha-49d831d95c803d5fa8cc28f2ce6592db421a1fda
    forcestring: true
