---
image:
  tag: "sha-7bf1d77362db66ab2ef3a7fdab1a4db315e7eb70"

# QoS: Burstable (Low Latency / CPU Bursting)
resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    memory: 256Mi

pdb:
  enabled: true
  minAvailable: 1

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - sky-fe-prd
          topologyKey: kubernetes.io/hostname
