---
helm:
  parameters:
  - name: image.name
    value: skyacrprodel5zpw.azurecr.io/sky-poc-backend
    forcestring: true
  - name: image.tag
    value: sha-d6a36ed
    forcestring: true

# QoS: Burstable (Low Latency / CPU Bursting)
resources:
  requests:
    cpu: 100m
    memory: 1024Mi
  limits:
    memory: 1024Mi

pdb:
  enabled: true
  minAvailable: 1

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - sky-be-prd
          topologyKey: kubernetes.io/hostname
