---
{{- if .Values.prometheusRules.kubernetes.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-alerts
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    prometheus: kube-prometheus-stack
    role: alert-rules
spec:
  groups:
    {{- toYaml .Values.prometheusRules.kubernetes.groups | nindent 4 }}
{{- end }}
---
{{- if .Values.prometheusRules.application.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: application-alerts
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    prometheus: kube-prometheus-stack
    role: alert-rules
spec:
  groups:
    {{- toYaml .Values.prometheusRules.application.groups | nindent 4 }}
{{- end }}
---
{{- if .Values.prometheusRules.goldenSignals.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre-golden-signals
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    prometheus: kube-prometheus-stack
    role: alert-rules
spec:
  groups:
    {{- toYaml .Values.prometheusRules.goldenSignals.groups | nindent 4 }}
{{- end }}
---
{{- if .Values.prometheusRules.backup.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backup-alerts
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    prometheus: kube-prometheus-stack
    role: alert-rules
spec:
  groups:
    {{- toYaml .Values.prometheusRules.backup.groups | nindent 4 }}
{{- end }}
