apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://akv-sky-staging-574052c0.vault.azure.net" # Needs templating or manual update currently
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
