---
extends: default

ignore: |
  gitops/charts/
  **.chart/
  **/templates/
  scripts/

rules:
  line-length:
    max: 300
    allow-non-breakable-words: true
  document-start: disable
  truthy: disable
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2
    indent-sequences: true
  key-duplicates: enable
  empty-lines:
    max: 2
