extends: default

ignore: |
  gitops/charts/
  **.chart/
  **/templates/
  .github/workflows/

rules:
  line-length: disable
  document-start: disable
  truthy: disable
  braces: disable
  brackets: disable
  colons: disable
  hyphens: disable
  indentation: disable
  key-duplicates: disable
  empty-lines: disable
