---
apiVersion: v2
name: observability
description: Stack de observabilidade customizada (ServiceMonitors, Alertas, Dashboards)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - observability
  - prometheus
  - grafana
  - loki
  - monitoring
maintainers:
  - name: DevOps Team
