---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sky-stg-unified-ingress
  namespace: staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleRemoveById 949110
spec:
  ingressClassName: nginx
  tls:
    - secretName: sky-stg-unified-tls
      hosts:
        - workspace-stg.skyfirstlabs.com
  rules:
    - host: workspace-stg.skyfirstlabs.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sky-be-stg-common-app
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sky-fe-stg-common-app
                port:
                  number: 80
