#!/bin/bash
set -e

# Usage: ./update-image-tag.sh <app-name> <new-tag> <gitops-repo-path>

APP_NAME=$1
NEW_TAG=$2
GITOPS_PATH=${3:-"./gitops"}

if [ -z "$APP_NAME" ] || [ -z "$NEW_TAG" ]; then
  echo "Usage: $0 <app-name> <new-tag>"
  exit 1
fi

echo "Updating $APP_NAME to version $NEW_TAG..."

# Find the yaml file containing the image definition
# Assumes structure gitops/apps/<app_name>/deployment.yaml or similar
# Using sed for compatibility (yq would be better but requires install)

# Example strategy: Look for 'image: .*<app_name>.*' and replace the tag
# This is a bit fragile with sed, specifically targeting a known structure helps.
# Assuming standard K8s deployment.

# Define the file path (adjust as per actual structure)
# Define the file path (Targeting ArgoCD Application Manifest)
FILE_PATH="$GITOPS_PATH/bootstrap/$APP_NAME.yaml"

if [ ! -f "$FILE_PATH" ]; then
  echo "Error: ArgoCD Application file not found at $FILE_PATH"
  exit 1
fi

# Regex Replace for image tag inside the Helm values block
# Pattern: looking for 'tag: ".*"' after 'repository: ...'
# Since it's a multiline string in yaml, we can use a simpler approach if we assume unique image names.
# Or use python/yq. For bash/sed, we'll try to match the specific line known to be generated by us.

if [[ "$OSTYPE" == "darwin"* ]]; then
  # Mac OS sed requires empty extension for -i
  sed -i '' "s|tag: \".*\"|tag: \"$NEW_TAG\"|g" "$FILE_PATH"
else
  sed -i "s|tag: \".*\"|tag: \"$NEW_TAG\"|g" "$FILE_PATH"
fi

echo "Updated $FILE_PATH to use tag $NEW_TAG"
