apiVersion: batch/v1
kind: Job
metadata:
  name: check-users-count
  namespace: staging
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      containers:
      - name: check-users
        image: skyacrstaging.azurecr.io/sky-poc-backend:latest
        command: ["python3"]
        args:
        - "-c"
        - |
          import asyncio
          import os
          from sqlalchemy.ext.asyncio import create_async_engine
          from sqlalchemy import text

          async def check():
              url = os.environ["DATABASE_URL"]
              print(f"Connecting to {url.split('@')[1]}") # Print host only for security
              engine = create_async_engine(url)
              async with engine.connect() as conn:
                  result = await conn.execute(text("SELECT count(*) FROM users"))
                  print(f"User Count: {result.scalar()}")

          if __name__ == "__main__":
             asyncio.run(check())
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sky-backend-staging-common-app-secrets
              key: database-url
      restartPolicy: Never
