---
apiVersion: batch/v1
kind: Job
metadata:
  name: manual-migration-verify-db
  namespace: staging
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      containers:
      - name: migrate
        image: skyacrstaging.azurecr.io/sky-poc-backend:latest
        command: ["alembic", "upgrade", "head"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sky-backend-staging-common-app-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: sky-backend-staging-common-app-secrets
              key: redis-url
        - name: REDIS_PORT
          value: "6379"
      restartPolicy: Never
